apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: apply-route
spec:
  workspaces:
    - name: source
  params:
    - name: NAME
      description: The name of the new app to deploy
      type: string
    - name: NAMESPACE
      description: The namespace to deploy this app to
      type: string
    - name: REPO_NAME
      description: The repository name this service is based on
      type: string
  steps:
    - name: apply-route
      image: openshift4/ose-client
      workingDir: /workspace/source
      command: ["/bin/bash", "-c"]
      args:
        - |
          cat<<EOF |oc apply -f -
          apiVersion: route.openshift.io/v1
          kind: Route
          metadata:
            name: $(params.NAME)
            namespace: $(params.NAMESPACE)
            labels:
              repo_name: $(params.REPO_NAME)
              pipelinesascode.tekton.dev/on-event: pull_request
              pipelinesascode.tekton.dev/on-target-branch: $(params.NAMESPACE)
          spec:
            host: $(params.NAME)-$(params.NAMESPACE).apps.mm-public.cfpb.p1.openshiftapps.com
            tls:
              termination: edge
            to:
              kind: Service
              name: $(params.NAME)
              weight: 100
            wildcardPolicy: None
          EOF
