apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  annotations:
    pipelinesascode.tekton.dev/max-keep-runs: "5"
    pipelinesascode.tekton.dev/on-event: pull_request
    pipelinesascode.tekton.dev/on-target-branch: development
    pipelinesascode.tekton.dev/task: '[git-clone, kaniko]'
  name: pipelinerun-pr-development
  namespace: development-pipelines
spec:
  params:
  - name: repo_url
    value: '{{ repo_url }}'
  - name: revision
    value: '{{ revision }}'
  - name: target_branch
    value: '{{ target_branch }}'
  - name: repo_name
    value: '{{ repo_name }}'
  - name: container_registry
    value: 'image-registry.openshift-image-registry.svc.cluster.local:5000'
  pipelineSpec:
    params:
    - name: repo_url
    - name: revision
    tasks:
    - name: fetch-repository
      params:
      - name: url
        value: $(params.repo_url)
      - name: revision
        value: $(params.revision)
      taskRef:
        kind: ClusterTask
        name: git-clone
      workspaces:
      - name: output
        workspace: source
      - name: basic-auth
        workspace: basic-auth
    - name: build-and-push-image
      taskRef:
        name: kaniko
        kind: Task
      runAfter:
        - fetch-repository
      workspaces:
        - name: source
          workspace: source
      params:
        - name: IMAGE
          value: $(params.container_registry)/$(params.target_branch)/$(params.repo_name):$(params.revision)
    workspaces:
    - name: source
    - name: basic-auth
  workspaces:
  - name: source
    volumeClaimTemplate:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
  - name: basic-auth
    secret:
      secretName: '{{ git_auth_secret }}'
