apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  annotations:
    pipelinesascode.tekton.dev/max-keep-runs: "5"
    pipelinesascode.tekton.dev/on-event: pull_request
    pipelinesascode.tekton.dev/on-target-branch: development
    pipelinesascode.tekton.dev/task: '[git-clone, kaniko]'
  name: pipelinerun-pr-development
  namespace: development-pipelines
spec:
  params:
  - name: repo_url
    value: '{{ repo_url }}'
  - name: revision
    value: '{{ revision }}'
  - name: pull_request_number
    value: '{{ pull_request_number }}'
  - name: target_branch
    value: '{{ target_branch }}'
  - name: source_branch
    value: '{{ source_branch }}'
  - name: repo_name
    value: '{{ repo_name }}'
  - name: container_registry
    value: 'image-registry.openshift-image-registry.svc.cluster.local:5000'
  pipelineSpec:
    params:
    - name: repo_url
    - name: revision
    - name: pull_request_number
    - name: target_branch
    - name: source_branch
    - name: repo_name
    - name: container_registry
    tasks:
    - name: fetch-repository
      taskRef:
        kind: ClusterTask
        name: git-clone
      workspaces:
      - name: output
        workspace: source
      - name: basic-auth
        workspace: basic-auth
      params:
      - name: url
        value: $(params.repo_url)
      - name: revision
        value: $(params.revision)
    - name: build-and-push-image
      taskRef:
        name: kaniko
        kind: Task
      runAfter:
        - fetch-repository
      workspaces:
        - name: source
          workspace: source
      params:
        - name: IMAGE
          value: $(params.container_registry)/$(params.target_branch)/$(params.repo_name):$(params.revision)
    - name: apply-deployment
      taskRef:
        name: apply-deployment
        kind: Task
      runAfter:
        - build-and-push-image
      workspaces:
        - name: source
          workspace: source
      params:
        - name: IMAGE
          value: $(tasks.build-and-push-image.results.IMAGE_URL)
        - name: NAME
          value: $(params.repo_name)-pull-$(params.pull_request_number)
        - name: NAMESPACE
          value: $(params.target_branch)
        - name: REPO_NAME
          value: $(params.repo_name)
    - name: apply-service
      taskRef:
        name: apply-service
        kind: Task
      runAfter:
        - build-and-push-image
      workspaces:
        - name: source
          workspace: source
      params:
        - name: NAME
          value: $(params.repo_name)-pull-$(params.pull_request_number)
        - name: NAMESPACE
          value: $(params.target_branch)
        - name: REPO_NAME
          value: $(params.repo_name)
    - name: create-route-edge
      taskRef:
        name: create-route-edge
        kind: Task
      runAfter:
        - apply-deployment
        - apply-service
      workspaces:
        - name: source
          workspace: source
      params:
        - name: NAME
          value: $(params.repo_name)-pull-$(params.pull_request_number)
        - name: NAMESPACE
          value: $(params.target_branch)
    workspaces:
    - name: source
    - name: basic-auth
  workspaces:
  - name: source
    volumeClaimTemplate:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
  - name: basic-auth
    secret:
      secretName: '{{ git_auth_secret }}'
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: apply-deployment
spec: 
  workspaces:
  - name: source
  params:
    - name: IMAGE
      description: The full registry path of the image to deploy
      type: string
    - name: NAME
      description: The name of the new app to deploy
      type: string
    - name: NAMESPACE
      description: The namespace to deploy this app to
      type: string
    - name: REPO_NAME
      description: The repository name this service is based on
      type: string
  steps:
    - name: apply-deployment
      image: image-registry.openshift-image-registry.svc.cluster.local:5000/openshift/cli:latest
      workingDir: /workspace/source
      command: ["/bin/bash", "-c"]
      args:
        - |
          cat<<EOF |oc apply -f -
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: $(params.NAME)
            namespace: $(params.NAMESPACE)
            labels:
              repo_name: $(params.REPO_NAME)
              pipelinesascode.tekton.dev/on-event: pull_request
              pipelinesascode.tekton.dev/on-target-branch: $(params.NAMESPACE)
          spec:
            replicas: 1
            selector:
              matchLabels:
                app: $(params.NAME)
            template:
              metadata:
                labels:
                  app: $(params.NAME)
              spec:
                containers:
                - name: $(params.NAME)
                  image: $(params.IMAGE)
                  ports:
                  - containerPort: 8080
          EOF
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: apply-service
spec: 
  workspaces:
  - name: source
  params:
    - name: NAME
      description: The name of the new app to deploy
      type: string
    - name: NAMESPACE
      description: The namespace to deploy this app to
      type: string
    - name: REPO_NAME
      description: The repository name this service is based on
      type: string
  steps:
    - name: apply-service
      image: image-registry.openshift-image-registry.svc.cluster.local:5000/openshift/cli:latest
      workingDir: /workspace/source
      command: ["/bin/bash", "-c"]
      args:
        - |
          cat<<EOF |oc apply -f -
          apiVersion: v1
          kind: Service
          metadata:
            name: $(params.NAME)
            namespace: $(params.NAMESPACE)
            labels:
              repo_name: $(params.REPO_NAME)
              pipelinesascode.tekton.dev/on-event: pull_request
              pipelinesascode.tekton.dev/on-target-branch: $(params.NAMESPACE)
          spec:
            selector:
              app: $(params.NAME)
            ports:
              - protocol: TCP
                port: 80
                targetPort: 8080
          EOF
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: create-route-edge
spec: 
  workspaces:
  - name: source
  params:
    - name: NAME
      description: The name of the new app to deploy
      type: string
    - name: NAMESPACE
      description: The namespace to deploy this app to
      type: string
  steps:
    - name: create-route-edge
      image: image-registry.openshift-image-registry.svc.cluster.local:5000/openshift/cli:latest
      workingDir: /workspace/source
      command: ["/bin/bash", "-c"]
      args:
        - |
          oc create route edge --service=$(params.NAME) --namespace=$(params.NAMESPACE)